name: API test CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
      runs-on: ubuntu-latest


      steps:
      - uses: actions/checkout@v2
      - name: set up JDK 21
        uses: actions/setup-java@v2
        with:
            java-version: '21'
            distribution: 'adopt'
            
      - name: Build with Maven
        run: mvn clean test
      - name: Publish Test Report
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-report
          path: target/surefire-reports
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: 'Pipeline finished with status: ${{ job.status }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      if: always()
